// Mocks generated by Mockito 5.4.6 from annotations
// in services/src/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:io' as _i16;
import 'dart:math' as _i15;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:constants/constants.dart' as _i13;
import 'package:firebase_analytics/firebase_analytics.dart' as _i8;
import 'package:firebase_auth/firebase_auth.dart' as _i14;
import 'package:firebase_messaging/firebase_messaging.dart' as _i17;
import 'package:firebase_storage/firebase_storage.dart' as _i7;
import 'package:flutter_image_compress/flutter_image_compress.dart' as _i18;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i9;
import 'package:hive_ce/hive.dart' as _i6;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:models/models.dart' as _i3;
import 'package:services/services.dart' as _i10;
import 'package:stacked/stacked.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDisplayPreferences_1 extends _i1.SmartFake
    implements _i3.DisplayPreferences {
  _FakeDisplayPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_2<T extends Object?> extends _i1.SmartFake
    implements _i4.CollectionReference<T> {
  _FakeCollectionReference_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_3 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactiveList_4<E> extends _i1.SmartFake
    implements _i5.ReactiveList<E> {
  _FakeReactiveList_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBox_5<E> extends _i1.SmartFake implements _i6.Box<E> {
  _FakeBox_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReference_6 extends _i1.SmartFake implements _i7.Reference {
  _FakeReference_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReport_7 extends _i1.SmartFake implements _i3.Report {
  _FakeReport_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImageMetadata_8 extends _i1.SmartFake implements _i3.ImageMetadata {
  _FakeImageMetadata_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAnalyticsObserver_9 extends _i1.SmartFake
    implements _i8.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationDetails_10 extends _i1.SmartFake
    implements _i9.NotificationDetails {
  _FakeNotificationDetails_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i10.UserService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(
            Invocation.getter(#log),
            returnValue: _FakeLogger_0(this, Invocation.getter(#log)),
            returnValueForMissingStub: _FakeLogger_0(
              this,
              Invocation.getter(#log),
            ),
          )
          as _i2.Logger);

  @override
  String get collectionPath =>
      (super.noSuchMethod(
            Invocation.getter(#collectionPath),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
          )
          as String);

  @override
  _i12.Stream<_i3.UserModel?> get currentUserStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserStream),
            returnValue: _i12.Stream<_i3.UserModel?>.empty(),
            returnValueForMissingStub: _i12.Stream<_i3.UserModel?>.empty(),
          )
          as _i12.Stream<_i3.UserModel?>);

  @override
  _i12.Stream<bool> get userInitializedStream =>
      (super.noSuchMethod(
            Invocation.getter(#userInitializedStream),
            returnValue: _i12.Stream<bool>.empty(),
            returnValueForMissingStub: _i12.Stream<bool>.empty(),
          )
          as _i12.Stream<bool>);

  @override
  _i3.DisplayPreferences get displayPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#displayPreferences),
            returnValue: _FakeDisplayPreferences_1(
              this,
              Invocation.getter(#displayPreferences),
            ),
            returnValueForMissingStub: _FakeDisplayPreferences_1(
              this,
              Invocation.getter(#displayPreferences),
            ),
          )
          as _i3.DisplayPreferences);

  @override
  bool get hasUser =>
      (super.noSuchMethod(
            Invocation.getter(#hasUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.CollectionReference<_i3.UserModel> get collectionReference =>
      (super.noSuchMethod(
            Invocation.getter(#collectionReference),
            returnValue: _FakeCollectionReference_2<_i3.UserModel>(
              this,
              Invocation.getter(#collectionReference),
            ),
            returnValueForMissingStub:
                _FakeCollectionReference_2<_i3.UserModel>(
                  this,
                  Invocation.getter(#collectionReference),
                ),
          )
          as _i4.CollectionReference<_i3.UserModel>);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.UserModel convertFromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#convertFromJson, [json]),
            returnValue: _FakeUserModel_3(
              this,
              Invocation.method(#convertFromJson, [json]),
            ),
            returnValueForMissingStub: _FakeUserModel_3(
              this,
              Invocation.method(#convertFromJson, [json]),
            ),
          )
          as _i3.UserModel);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setDisplayPreferences(
    _i3.DisplayPreferences? displayPreferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDisplayPreferences, [displayPreferences]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setLanguage(_i13.LanguageType? language) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [language]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setAppearance(_i13.AppearanceMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setAppearance, [mode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void onAuthenticated(_i14.User? user) => super.noSuchMethod(
    Invocation.method(#onAuthenticated, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void onUnauthenticated() => super.noSuchMethod(
    Invocation.method(#onUnauthenticated, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> waitUntilUserIsReady() =>
      (super.noSuchMethod(
            Invocation.method(#waitUntilUserIsReady, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncUser() =>
      (super.noSuchMethod(
            Invocation.method(#syncUser, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncExternalServices() =>
      (super.noSuchMethod(
            Invocation.method(#syncExternalServices, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> createUser({
    required String? firstName,
    required String? lastName,
    required String? country,
    required String? state,
    required String? city,
    required String? appSource,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #firstName: firstName,
              #lastName: lastName,
              #country: country,
              #state: state,
              #city: city,
              #appSource: appSource,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateUser(_i3.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearUserSessionData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserSessionData, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  String generateNewDocId() =>
      (super.noSuchMethod(
            Invocation.method(#generateNewDocId, []),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#generateNewDocId, []),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#generateNewDocId, []),
            ),
          )
          as String);

  @override
  _i12.Future<bool> documentExists({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#documentExists, [], {#documentId: documentId}),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> create({
    required _i3.UserModel? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #payload: payload,
              #documentId: documentId,
              #verbose: verbose,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.UserModel?> get(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [documentId]),
            returnValue: _i12.Future<_i3.UserModel?>.value(),
            returnValueForMissingStub: _i12.Future<_i3.UserModel?>.value(),
          )
          as _i12.Future<_i3.UserModel?>);

  @override
  _i12.Future<List<_i3.UserModel>> getDocuments({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [], {#limit: limit}),
            returnValue: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i12.Future<List<_i3.UserModel>>);

  @override
  _i12.Future<List<_i3.UserModel>> getDocumentsWithQuery({
    required _i4.Query<_i3.UserModel>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentsWithQuery, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i12.Future<List<_i3.UserModel>>);

  @override
  _i12.Future<void> update({
    required String? documentId,
    required _i3.UserModel? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> onlyUpdate({
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onlyUpdate, [], {
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> delete({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#documentId: documentId}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<_i3.UserModel?> subscribe({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {#documentId: documentId}),
            returnValue: _i12.Stream<_i3.UserModel?>.empty(),
            returnValueForMissingStub: _i12.Stream<_i3.UserModel?>.empty(),
          )
          as _i12.Stream<_i3.UserModel?>);

  @override
  _i12.Stream<List<_i3.UserModel>> subscribeList({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeList, [], {#limit: limit}),
            returnValue: _i12.Stream<List<_i3.UserModel>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i12.Stream<List<_i3.UserModel>>);

  @override
  _i12.Stream<List<_i3.UserModel>> subscribeListWithQuery({
    required _i4.Query<_i3.UserModel>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeListWithQuery, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Stream<List<_i3.UserModel>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i12.Stream<List<_i3.UserModel>>);

  @override
  String newDocId({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#newDocId, [], {
              #collectionReference: collectionReference,
            }),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#newDocId, [], {
                #collectionReference: collectionReference,
              }),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#newDocId, [], {
                #collectionReference: collectionReference,
              }),
            ),
          )
          as String);

  @override
  _i12.Future<void> createDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required _i3.UserModel? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDocument, [], {
              #collectionReference: collectionReference,
              #payload: payload,
              #documentId: documentId,
              #verbose: verbose,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.UserModel?> findDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
            }),
            returnValue: _i12.Future<_i3.UserModel?>.value(),
            returnValueForMissingStub: _i12.Future<_i3.UserModel?>.value(),
          )
          as _i12.Future<_i3.UserModel?>);

  @override
  _i12.Future<List<_i3.UserModel>> fetchDocuments({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDocuments, [], {
              #collectionReference: collectionReference,
              #limit: limit,
            }),
            returnValue: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i12.Future<List<_i3.UserModel>>);

  @override
  _i12.Future<List<_i3.UserModel>> fetchDocumentsWithQuery({
    required _i4.Query<_i3.UserModel>? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDocumentsWithQuery, [], {#query: query}),
            returnValue: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
            returnValueForMissingStub: _i12.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i12.Future<List<_i3.UserModel>>);

  @override
  _i12.Future<void> updateDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
    required _i3.UserModel? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateOnlyDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnlyDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<_i3.UserModel?> subscribeToDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
            }),
            returnValue: _i12.Stream<_i3.UserModel?>.empty(),
            returnValueForMissingStub: _i12.Stream<_i3.UserModel?>.empty(),
          )
          as _i12.Stream<_i3.UserModel?>);

  @override
  _i12.Stream<List<_i3.UserModel>> subscribeToList({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToList, [], {
              #collectionReference: collectionReference,
              #limit: limit,
            }),
            returnValue: _i12.Stream<List<_i3.UserModel>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i12.Stream<List<_i3.UserModel>>);

  @override
  _i12.Stream<List<_i3.UserModel>> subscribeToListWithQuery({
    required _i4.Query<_i3.UserModel>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToListWithQuery, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Stream<List<_i3.UserModel>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.UserModel>>.empty(),
          )
          as _i12.Stream<List<_i3.UserModel>>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i10.AuthenticationService {
  @override
  List<String> get linkedProviders =>
      (super.noSuchMethod(
            Invocation.getter(#linkedProviders),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get hasGoogleProvider =>
      (super.noSuchMethod(
            Invocation.getter(#hasGoogleProvider),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasAppleProvider =>
      (super.noSuchMethod(
            Invocation.getter(#hasAppleProvider),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasPasswordProvider =>
      (super.noSuchMethod(
            Invocation.getter(#hasPasswordProvider),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  ({String? firstName, String? lastName}) get userName =>
      (super.noSuchMethod(
            Invocation.getter(#userName),
            returnValue: (firstName: null, lastName: null),
            returnValueForMissingStub: (firstName: null, lastName: null),
          )
          as ({String? firstName, String? lastName}));

  @override
  bool get hasFirebaseUser =>
      (super.noSuchMethod(
            Invocation.getter(#hasFirebaseUser),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAppleSignInAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isAppleSignInAvailable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Stream<_i10.AuthState> get authenticatedStream =>
      (super.noSuchMethod(
            Invocation.getter(#authenticatedStream),
            returnValue: _i12.Stream<_i10.AuthState>.empty(),
            returnValueForMissingStub: _i12.Stream<_i10.AuthState>.empty(),
          )
          as _i12.Stream<_i10.AuthState>);

  @override
  String get currentUserAuthProvider =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserAuthProvider),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#currentUserAuthProvider),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#currentUserAuthProvider),
            ),
          )
          as String);

  @override
  bool get isProviderGoogle =>
      (super.noSuchMethod(
            Invocation.getter(#isProviderGoogle),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isProviderApple =>
      (super.noSuchMethod(
            Invocation.getter(#isProviderApple),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isProviderEmail =>
      (super.noSuchMethod(
            Invocation.getter(#isProviderEmail),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.Future<bool> get canSignInWithApple =>
      (super.noSuchMethod(
            Invocation.getter(#canSignInWithApple),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void setAuthStateToIdle() => super.noSuchMethod(
    Invocation.method(#setAuthStateToIdle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> initializeGoogleSignIn() =>
      (super.noSuchMethod(
            Invocation.method(#initializeGoogleSignIn, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> ensureGoogleSignInInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureGoogleSignInInitialized, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearFirebaseUserOnFreshInstall() =>
      (super.noSuchMethod(
            Invocation.method(#clearFirebaseUserOnFreshInstall, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openAddAccountSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAddAccountSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addObserver(_i10.AuthObserver? observer) => super.noSuchMethod(
    Invocation.method(#addObserver, [observer]),
    returnValueForMissingStub: null,
  );

  @override
  void removeObserver(_i10.AuthObserver? observer) => super.noSuchMethod(
    Invocation.method(#removeObserver, [observer]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> continueWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#continueWithGoogle, []),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> linkGoogleToCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#linkGoogleToCurrentUser, []),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  String sha256HashNonce(String? nonce) =>
      (super.noSuchMethod(
            Invocation.method(#sha256HashNonce, [nonce]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#sha256HashNonce, [nonce]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#sha256HashNonce, [nonce]),
            ),
          )
          as String);

  @override
  String nonceString(int? length, [_i15.Random? randomSecure]) =>
      (super.noSuchMethod(
            Invocation.method(#nonceString, [length, randomSecure]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#nonceString, [length, randomSecure]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#nonceString, [length, randomSecure]),
            ),
          )
          as String);

  @override
  _i12.Future<bool> continueWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#continueWithApple, []),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> reauthenticateUser({required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateUser, [], {#password: password}),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> reauthenticateUserWithProvider() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateUserWithProvider, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  String exceptionToMessage([dynamic exception]) =>
      (super.noSuchMethod(
            Invocation.method(#exceptionToMessage, [exception]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#exceptionToMessage, [exception]),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#exceptionToMessage, [exception]),
            ),
          )
          as String);
}

/// A class which mocks [AlertService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertService extends _i1.Mock implements _i10.AlertService {
  @override
  _i5.ReactiveList<_i10.AlertMixin> get alertListeners =>
      (super.noSuchMethod(
            Invocation.getter(#alertListeners),
            returnValue: _FakeReactiveList_4<_i10.AlertMixin>(
              this,
              Invocation.getter(#alertListeners),
            ),
            returnValueForMissingStub: _FakeReactiveList_4<_i10.AlertMixin>(
              this,
              Invocation.getter(#alertListeners),
            ),
          )
          as _i5.ReactiveList<_i10.AlertMixin>);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void addAlertListener(_i10.AlertMixin? listener) => super.noSuchMethod(
    Invocation.method(#addAlertListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAlertListeners(_i3.AlertModel? alertmodel) => super.noSuchMethod(
    Invocation.method(#notifyAlertListeners, [alertmodel]),
    returnValueForMissingStub: null,
  );

  @override
  void showSuccessAlert({required String? title, required String? message}) =>
      super.noSuchMethod(
        Invocation.method(#showSuccessAlert, [], {
          #title: title,
          #message: message,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void showInfoAlert({required String? title, required String? message}) =>
      super.noSuchMethod(
        Invocation.method(#showInfoAlert, [], {
          #title: title,
          #message: message,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void showWarningAlert({required String? title, required String? message}) =>
      super.noSuchMethod(
        Invocation.method(#showWarningAlert, [], {
          #title: title,
          #message: message,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void showErrorAlert({required String? title, required String? message}) =>
      super.noSuchMethod(
        Invocation.method(#showErrorAlert, [], {
          #title: title,
          #message: message,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void showAlert(_i3.AlertModel? alert) => super.noSuchMethod(
    Invocation.method(#showAlert, [alert]),
    returnValueForMissingStub: null,
  );

  @override
  void showToast(String? message) => super.noSuchMethod(
    Invocation.method(#showToast, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SettingsStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsStorageService extends _i1.Mock
    implements _i10.SettingsStorageService {
  @override
  bool get freshInstall =>
      (super.noSuchMethod(
            Invocation.getter(#freshInstall),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.DisplayPreferences get displayPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#displayPreferences),
            returnValue: _FakeDisplayPreferences_1(
              this,
              Invocation.getter(#displayPreferences),
            ),
            returnValueForMissingStub: _FakeDisplayPreferences_1(
              this,
              Invocation.getter(#displayPreferences),
            ),
          )
          as _i3.DisplayPreferences);

  @override
  _i6.Box<dynamic> get box =>
      (super.noSuchMethod(
            Invocation.getter(#box),
            returnValue: _FakeBox_5<dynamic>(this, Invocation.getter(#box)),
            returnValueForMissingStub: _FakeBox_5<dynamic>(
              this,
              Invocation.getter(#box),
            ),
          )
          as _i6.Box<dynamic>);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
            returnValueForMissingStub: _FakeLogger_0(
              this,
              Invocation.getter(#logger),
            ),
          )
          as _i2.Logger);

  @override
  void setFreshInstall() => super.noSuchMethod(
    Invocation.method(#setFreshInstall, []),
    returnValueForMissingStub: null,
  );

  @override
  void setDisplayPreferences(_i3.DisplayPreferences? displayPreferences) =>
      super.noSuchMethod(
        Invocation.method(#setDisplayPreferences, [displayPreferences]),
        returnValueForMissingStub: null,
      );

  @override
  void saveData(String? key, dynamic value) => super.noSuchMethod(
    Invocation.method(#saveData, [key, value]),
    returnValueForMissingStub: null,
  );

  @override
  T getData<T>(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [key]),
            returnValue: _i11.dummyValue<T>(
              this,
              Invocation.method(#getData, [key]),
            ),
            returnValueForMissingStub: _i11.dummyValue<T>(
              this,
              Invocation.method(#getData, [key]),
            ),
          )
          as T);

  @override
  _i12.Future<void> deleteData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteData, [key]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void deleteAllData() => super.noSuchMethod(
    Invocation.method(#deleteAllData, []),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Stream<T> watch<T>() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i12.Stream<T>.empty(),
            returnValueForMissingStub: _i12.Stream<T>.empty(),
          )
          as _i12.Stream<T>);
}

/// A class which mocks [UrlLauncherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLauncherService extends _i1.Mock
    implements _i10.UrlLauncherService {
  @override
  _i12.Future<void> sendEmail(String? email, {String? query}) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmail, [email], {#query: query}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openUrl(String? url, {bool? openInBrowser = false}) =>
      (super.noSuchMethod(
            Invocation.method(#openUrl, [url], {#openInBrowser: openInBrowser}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openEmailAppChooser() =>
      (super.noSuchMethod(
            Invocation.method(#openEmailAppChooser, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [ReportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportService extends _i1.Mock implements _i10.ReportService {
  @override
  _i2.Logger get log =>
      (super.noSuchMethod(
            Invocation.getter(#log),
            returnValue: _FakeLogger_0(this, Invocation.getter(#log)),
            returnValueForMissingStub: _FakeLogger_0(
              this,
              Invocation.getter(#log),
            ),
          )
          as _i2.Logger);

  @override
  String get collectionPath =>
      (super.noSuchMethod(
            Invocation.getter(#collectionPath),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
          )
          as String);

  @override
  List<_i3.Report> get reportList =>
      (super.noSuchMethod(
            Invocation.getter(#reportList),
            returnValue: <_i3.Report>[],
            returnValueForMissingStub: <_i3.Report>[],
          )
          as List<_i3.Report>);

  @override
  _i12.Stream<List<_i3.Report>> get reportsStream =>
      (super.noSuchMethod(
            Invocation.getter(#reportsStream),
            returnValue: _i12.Stream<List<_i3.Report>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.Report>>.empty(),
          )
          as _i12.Stream<List<_i3.Report>>);

  @override
  _i4.CollectionReference<_i3.Report> get collectionReference =>
      (super.noSuchMethod(
            Invocation.getter(#collectionReference),
            returnValue: _FakeCollectionReference_2<_i3.Report>(
              this,
              Invocation.getter(#collectionReference),
            ),
            returnValueForMissingStub: _FakeCollectionReference_2<_i3.Report>(
              this,
              Invocation.getter(#collectionReference),
            ),
          )
          as _i4.CollectionReference<_i3.Report>);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Reference get storageReference =>
      (super.noSuchMethod(
            Invocation.getter(#storageReference),
            returnValue: _FakeReference_6(
              this,
              Invocation.getter(#storageReference),
            ),
            returnValueForMissingStub: _FakeReference_6(
              this,
              Invocation.getter(#storageReference),
            ),
          )
          as _i7.Reference);

  @override
  _i3.Report convertFromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#convertFromJson, [json]),
            returnValue: _FakeReport_7(
              this,
              Invocation.method(#convertFromJson, [json]),
            ),
            returnValueForMissingStub: _FakeReport_7(
              this,
              Invocation.method(#convertFromJson, [json]),
            ),
          )
          as _i3.Report);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncReportList() =>
      (super.noSuchMethod(
            Invocation.method(#syncReportList, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addReport(_i3.Report? report) =>
      (super.noSuchMethod(
            Invocation.method(#addReport, [report]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateReport(_i3.Report? report) =>
      (super.noSuchMethod(
            Invocation.method(#updateReport, [report]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i3.Report>> fetchReports() =>
      (super.noSuchMethod(
            Invocation.method(#fetchReports, []),
            returnValue: _i12.Future<List<_i3.Report>>.value(<_i3.Report>[]),
            returnValueForMissingStub: _i12.Future<List<_i3.Report>>.value(
              <_i3.Report>[],
            ),
          )
          as _i12.Future<List<_i3.Report>>);

  @override
  _i12.Future<void> fetchReportByIds(List<String>? reportIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchReportByIds, [reportIds]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> seedFakeReports() =>
      (super.noSuchMethod(
            Invocation.method(#seedFakeReports, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  String generateNewDocId() =>
      (super.noSuchMethod(
            Invocation.method(#generateNewDocId, []),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#generateNewDocId, []),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#generateNewDocId, []),
            ),
          )
          as String);

  @override
  _i12.Future<bool> documentExists({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#documentExists, [], {#documentId: documentId}),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> create({
    required _i3.Report? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #payload: payload,
              #documentId: documentId,
              #verbose: verbose,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.Report?> get(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#get, [documentId]),
            returnValue: _i12.Future<_i3.Report?>.value(),
            returnValueForMissingStub: _i12.Future<_i3.Report?>.value(),
          )
          as _i12.Future<_i3.Report?>);

  @override
  _i12.Future<List<_i3.Report>> getDocuments({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [], {#limit: limit}),
            returnValue: _i12.Future<List<_i3.Report>>.value(<_i3.Report>[]),
            returnValueForMissingStub: _i12.Future<List<_i3.Report>>.value(
              <_i3.Report>[],
            ),
          )
          as _i12.Future<List<_i3.Report>>);

  @override
  _i12.Future<List<_i3.Report>> getDocumentsWithQuery({
    required _i4.Query<_i3.Report>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentsWithQuery, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Future<List<_i3.Report>>.value(<_i3.Report>[]),
            returnValueForMissingStub: _i12.Future<List<_i3.Report>>.value(
              <_i3.Report>[],
            ),
          )
          as _i12.Future<List<_i3.Report>>);

  @override
  _i12.Future<void> update({
    required String? documentId,
    required _i3.Report? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [], {
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> onlyUpdate({
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onlyUpdate, [], {
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> delete({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#documentId: documentId}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<_i3.Report?> subscribe({required String? documentId}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {#documentId: documentId}),
            returnValue: _i12.Stream<_i3.Report?>.empty(),
            returnValueForMissingStub: _i12.Stream<_i3.Report?>.empty(),
          )
          as _i12.Stream<_i3.Report?>);

  @override
  _i12.Stream<List<_i3.Report>> subscribeList({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeList, [], {#limit: limit}),
            returnValue: _i12.Stream<List<_i3.Report>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.Report>>.empty(),
          )
          as _i12.Stream<List<_i3.Report>>);

  @override
  _i12.Stream<List<_i3.Report>> subscribeListWithQuery({
    required _i4.Query<_i3.Report>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeListWithQuery, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Stream<List<_i3.Report>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.Report>>.empty(),
          )
          as _i12.Stream<List<_i3.Report>>);

  @override
  String newDocId({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#newDocId, [], {
              #collectionReference: collectionReference,
            }),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#newDocId, [], {
                #collectionReference: collectionReference,
              }),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.method(#newDocId, [], {
                #collectionReference: collectionReference,
              }),
            ),
          )
          as String);

  @override
  _i12.Future<void> createDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required _i3.Report? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDocument, [], {
              #collectionReference: collectionReference,
              #payload: payload,
              #documentId: documentId,
              #verbose: verbose,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.Report?> findDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
            }),
            returnValue: _i12.Future<_i3.Report?>.value(),
            returnValueForMissingStub: _i12.Future<_i3.Report?>.value(),
          )
          as _i12.Future<_i3.Report?>);

  @override
  _i12.Future<List<_i3.Report>> fetchDocuments({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDocuments, [], {
              #collectionReference: collectionReference,
              #limit: limit,
            }),
            returnValue: _i12.Future<List<_i3.Report>>.value(<_i3.Report>[]),
            returnValueForMissingStub: _i12.Future<List<_i3.Report>>.value(
              <_i3.Report>[],
            ),
          )
          as _i12.Future<List<_i3.Report>>);

  @override
  _i12.Future<List<_i3.Report>> fetchDocumentsWithQuery({
    required _i4.Query<_i3.Report>? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDocumentsWithQuery, [], {#query: query}),
            returnValue: _i12.Future<List<_i3.Report>>.value(<_i3.Report>[]),
            returnValueForMissingStub: _i12.Future<List<_i3.Report>>.value(
              <_i3.Report>[],
            ),
          )
          as _i12.Future<List<_i3.Report>>);

  @override
  _i12.Future<void> updateDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
    required _i3.Report? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateOnlyDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnlyDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
              #payload: payload,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<_i3.Report?> subscribeToDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToDocument, [], {
              #collectionReference: collectionReference,
              #documentId: documentId,
            }),
            returnValue: _i12.Stream<_i3.Report?>.empty(),
            returnValueForMissingStub: _i12.Stream<_i3.Report?>.empty(),
          )
          as _i12.Stream<_i3.Report?>);

  @override
  _i12.Stream<List<_i3.Report>> subscribeToList({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToList, [], {
              #collectionReference: collectionReference,
              #limit: limit,
            }),
            returnValue: _i12.Stream<List<_i3.Report>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.Report>>.empty(),
          )
          as _i12.Stream<List<_i3.Report>>);

  @override
  _i12.Stream<List<_i3.Report>> subscribeToListWithQuery({
    required _i4.Query<_i3.Report>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToListWithQuery, [], {
              #query: query,
              #limit: limit,
            }),
            returnValue: _i12.Stream<List<_i3.Report>>.empty(),
            returnValueForMissingStub: _i12.Stream<List<_i3.Report>>.empty(),
          )
          as _i12.Stream<List<_i3.Report>>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<bool> uploadFile({
    required _i16.File? file,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {#file: file, #userId: userId}),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<_i7.Reference>?> getUsersUploadedFiles({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersUploadedFiles, [], {#userId: userId}),
            returnValue: _i12.Future<List<_i7.Reference>?>.value(),
            returnValueForMissingStub:
                _i12.Future<List<_i7.Reference>?>.value(),
          )
          as _i12.Future<List<_i7.Reference>?>);

  @override
  _i12.Future<List<String>> getUsersUploadedFileUrls({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersUploadedFileUrls, [], {#userId: userId}),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i12.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i12.Future<List<String>>);
}

/// A class which mocks [MediaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaService extends _i1.Mock implements _i10.MediaService {
  @override
  _i12.Future<_i16.File?> pickImage({required _i13.AssetSource? source}) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {#source: source}),
            returnValue: _i12.Future<_i16.File?>.value(),
            returnValueForMissingStub: _i12.Future<_i16.File?>.value(),
          )
          as _i12.Future<_i16.File?>);

  @override
  _i12.Future<List<_i16.File?>> pickMultiImage() =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, []),
            returnValue: _i12.Future<List<_i16.File?>>.value(<_i16.File?>[]),
            returnValueForMissingStub: _i12.Future<List<_i16.File?>>.value(
              <_i16.File?>[],
            ),
          )
          as _i12.Future<List<_i16.File?>>);

  @override
  _i12.Future<_i3.ImageMetadata> extractImageMetadata(_i16.File? pickedFile) =>
      (super.noSuchMethod(
            Invocation.method(#extractImageMetadata, [pickedFile]),
            returnValue: _i12.Future<_i3.ImageMetadata>.value(
              _FakeImageMetadata_8(
                this,
                Invocation.method(#extractImageMetadata, [pickedFile]),
              ),
            ),
            returnValueForMissingStub: _i12.Future<_i3.ImageMetadata>.value(
              _FakeImageMetadata_8(
                this,
                Invocation.method(#extractImageMetadata, [pickedFile]),
              ),
            ),
          )
          as _i12.Future<_i3.ImageMetadata>);

  @override
  _i12.Future<_i16.File?> cropImage(_i16.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#cropImage, [imageFile]),
            returnValue: _i12.Future<_i16.File?>.value(),
            returnValueForMissingStub: _i12.Future<_i16.File?>.value(),
          )
          as _i12.Future<_i16.File?>);

  @override
  _i12.Future<_i3.ProcessedImage?> pickImageFromCamera() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromCamera, []),
            returnValue: _i12.Future<_i3.ProcessedImage?>.value(),
            returnValueForMissingStub: _i12.Future<_i3.ProcessedImage?>.value(),
          )
          as _i12.Future<_i3.ProcessedImage?>);

  @override
  _i12.Future<List<_i3.ProcessedImage?>> pickImagesFromGallery() =>
      (super.noSuchMethod(
            Invocation.method(#pickImagesFromGallery, []),
            returnValue: _i12.Future<List<_i3.ProcessedImage?>>.value(
              <_i3.ProcessedImage?>[],
            ),
            returnValueForMissingStub:
                _i12.Future<List<_i3.ProcessedImage?>>.value(
                  <_i3.ProcessedImage?>[],
                ),
          )
          as _i12.Future<List<_i3.ProcessedImage?>>);

  @override
  _i12.Future<_i16.File?> compressImage(_i16.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#compressImage, [imageFile]),
            returnValue: _i12.Future<_i16.File?>.value(),
            returnValueForMissingStub: _i12.Future<_i16.File?>.value(),
          )
          as _i12.Future<_i16.File?>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i10.PermissionService {
  @override
  bool get hasLocationPermission =>
      (super.noSuchMethod(
            Invocation.getter(#hasLocationPermission),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLocationPermissionDenied =>
      (super.noSuchMethod(
            Invocation.getter(#isLocationPermissionDenied),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasNotificationPermission =>
      (super.noSuchMethod(
            Invocation.getter(#hasNotificationPermission),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNotificationPermissionDenied =>
      (super.noSuchMethod(
            Invocation.getter(#isNotificationPermissionDenied),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasExceededNotificationDenials =>
      (super.noSuchMethod(
            Invocation.getter(#hasExceededNotificationDenials),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listenersCount =>
      (super.noSuchMethod(
            Invocation.getter(#listenersCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i12.Future<void> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> requestNotificationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationPermission, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openNotificationSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> refreshPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#refreshPermissions, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> requestPhotosPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPhotosPermission, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(#listenToReactiveValues, [reactiveValues]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i10.AnalyticsService {
  @override
  _i8.FirebaseAnalyticsObserver getAnalyticsObserver() =>
      (super.noSuchMethod(
            Invocation.method(#getAnalyticsObserver, []),
            returnValue: _FakeFirebaseAnalyticsObserver_9(
              this,
              Invocation.method(#getAnalyticsObserver, []),
            ),
            returnValueForMissingStub: _FakeFirebaseAnalyticsObserver_9(
              this,
              Invocation.method(#getAnalyticsObserver, []),
            ),
          )
          as _i8.FirebaseAnalyticsObserver);

  @override
  void logAppOpen() => super.noSuchMethod(
    Invocation.method(#logAppOpen, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> setUserId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setUserProperty({required String? name, String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void logLogin(String? method) => super.noSuchMethod(
    Invocation.method(#logLogin, [method]),
    returnValueForMissingStub: null,
  );

  @override
  void logSignUp(String? method) => super.noSuchMethod(
    Invocation.method(#logSignUp, [method]),
    returnValueForMissingStub: null,
  );

  @override
  void logOnboardingComplete() => super.noSuchMethod(
    Invocation.method(#logOnboardingComplete, []),
    returnValueForMissingStub: null,
  );

  @override
  void logButtonClick(String? buttonName) => super.noSuchMethod(
    Invocation.method(#logButtonClick, [buttonName]),
    returnValueForMissingStub: null,
  );

  @override
  void logScreenView({String? screenClass, String? screenName}) =>
      super.noSuchMethod(
        Invocation.method(#logScreenView, [], {
          #screenClass: screenClass,
          #screenName: screenName,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void trackEvent(String? eventName, {Map<String, Object>? parameters}) =>
      super.noSuchMethod(
        Invocation.method(#trackEvent, [eventName], {#parameters: parameters}),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PushNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPushNotificationService extends _i1.Mock
    implements _i10.PushNotificationService {
  @override
  _i12.Future<String?> get getFcmToken =>
      (super.noSuchMethod(
            Invocation.getter(#getFcmToken),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> initializeNotificationListeners() =>
      (super.noSuchMethod(
            Invocation.method(#initializeNotificationListeners, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> getInitialMessageAndHandle() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessageAndHandle, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void handleMessage(_i17.RemoteMessage? message) => super.noSuchMethod(
    Invocation.method(#handleMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void handleMessageOpened(_i17.RemoteMessage? message) => super.noSuchMethod(
    Invocation.method(#handleMessageOpened, [message]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock
    implements _i10.LocalNotificationService {
  @override
  _i12.Future<void> initLocalNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#initLocalNotifications, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i9.NotificationDetails getPlatformChannelDetails(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformChannelDetails, [type]),
            returnValue: _FakeNotificationDetails_10(
              this,
              Invocation.method(#getPlatformChannelDetails, [type]),
            ),
            returnValueForMissingStub: _FakeNotificationDetails_10(
              this,
              Invocation.method(#getPlatformChannelDetails, [type]),
            ),
          )
          as _i9.NotificationDetails);

  @override
  void handleOnTapNotification(_i17.RemoteMessage? message) =>
      super.noSuchMethod(
        Invocation.method(#handleOnTapNotification, [message]),
        returnValueForMissingStub: null,
      );

  @override
  void showNotification(_i17.RemoteMessage? message) => super.noSuchMethod(
    Invocation.method(#showNotification, [message]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CrashlyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsService extends _i1.Mock
    implements _i10.CrashlyticsService {
  @override
  _i12.Future<void> setUserIdToCrashlytics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserIdToCrashlytics, [userId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setUserEmailToCrashlytics(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#setUserEmailToCrashlytics, [email]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void setupUserProfile({String? userId, String? email}) => super.noSuchMethod(
    Invocation.method(#setupUserProfile, [], {#userId: userId, #email: email}),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> setupFlutterErrorLogging() =>
      (super.noSuchMethod(
            Invocation.method(#setupFlutterErrorLogging, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> logToCrashlytics(
    _i2.Level? level,
    List<String>? lines,
    StackTrace? stacktrace,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logToCrashlytics, [level, lines, stacktrace]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void crashApp() => super.noSuchMethod(
    Invocation.method(#crashApp, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CloudinaryStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudinaryStorageService extends _i1.Mock
    implements _i10.CloudinaryStorageService {
  @override
  String get uploadUrl =>
      (super.noSuchMethod(
            Invocation.getter(#uploadUrl),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#uploadUrl),
            ),
            returnValueForMissingStub: _i11.dummyValue<String>(
              this,
              Invocation.getter(#uploadUrl),
            ),
          )
          as String);

  @override
  _i12.Future<String?> uploadFile({
    required _i16.File? file,
    String? folder,
    String? publicIdPrefix,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #file: file,
              #folder: folder,
              #publicIdPrefix: publicIdPrefix,
            }),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<String?> uploadXFile({
    required _i18.XFile? xfile,
    String? folder,
    String? publicIdPrefix,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadXFile, [], {
              #xfile: xfile,
              #folder: folder,
              #publicIdPrefix: publicIdPrefix,
            }),
            returnValue: _i12.Future<String?>.value(),
            returnValueForMissingStub: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);
}
