// Mocks generated by Mockito 5.4.5 from annotations
// in services/src/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:math' as _i11;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i10;
import 'package:hive_ce/hive.dart' as _i6;
import 'package:logger/logger.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:models/models.dart' as _i3;
import 'package:services/services.dart' as _i7;
import 'package:stacked/stacked.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDisplayPreferences_1 extends _i1.SmartFake
    implements _i3.DisplayPreferences {
  _FakeDisplayPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_2<T extends Object?> extends _i1.SmartFake
    implements _i4.CollectionReference<T> {
  _FakeCollectionReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_3 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveList_4<E> extends _i1.SmartFake
    implements _i5.ReactiveList<E> {
  _FakeReactiveList_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBox_5<E> extends _i1.SmartFake implements _i6.Box<E> {
  _FakeBox_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReport_6 extends _i1.SmartFake implements _i3.Report {
  _FakeReport_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_7<T extends Object?> extends _i1.SmartFake
    implements _i4.Query<T> {
  _FakeQuery_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i7.UserService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  _i9.Stream<_i3.UserModel?> get currentUserStream => (super.noSuchMethod(
        Invocation.getter(#currentUserStream),
        returnValue: _i9.Stream<_i3.UserModel?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i3.UserModel?>.empty(),
      ) as _i9.Stream<_i3.UserModel?>);

  @override
  _i9.Stream<bool> get userInitializedStream => (super.noSuchMethod(
        Invocation.getter(#userInitializedStream),
        returnValue: _i9.Stream<bool>.empty(),
        returnValueForMissingStub: _i9.Stream<bool>.empty(),
      ) as _i9.Stream<bool>);

  @override
  _i3.DisplayPreferences get displayPreferences => (super.noSuchMethod(
        Invocation.getter(#displayPreferences),
        returnValue: _FakeDisplayPreferences_1(
          this,
          Invocation.getter(#displayPreferences),
        ),
        returnValueForMissingStub: _FakeDisplayPreferences_1(
          this,
          Invocation.getter(#displayPreferences),
        ),
      ) as _i3.DisplayPreferences);

  @override
  bool get hasUser => (super.noSuchMethod(
        Invocation.getter(#hasUser),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.CollectionReference<_i3.UserModel> get collectionReference =>
      (super.noSuchMethod(
        Invocation.getter(#collectionReference),
        returnValue: _FakeCollectionReference_2<_i3.UserModel>(
          this,
          Invocation.getter(#collectionReference),
        ),
        returnValueForMissingStub: _FakeCollectionReference_2<_i3.UserModel>(
          this,
          Invocation.getter(#collectionReference),
        ),
      ) as _i4.CollectionReference<_i3.UserModel>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.UserModel convertFromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertFromJson,
          [json],
        ),
        returnValue: _FakeUserModel_3(
          this,
          Invocation.method(
            #convertFromJson,
            [json],
          ),
        ),
        returnValueForMissingStub: _FakeUserModel_3(
          this,
          Invocation.method(
            #convertFromJson,
            [json],
          ),
        ),
      ) as _i3.UserModel);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void onAuthenticated(_i10.User? user) => super.noSuchMethod(
        Invocation.method(
          #onAuthenticated,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onUnauthenticated() => super.noSuchMethod(
        Invocation.method(
          #onUnauthenticated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> waitUntilUserIsReady() => (super.noSuchMethod(
        Invocation.method(
          #waitUntilUserIsReady,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> syncUser() => (super.noSuchMethod(
        Invocation.method(
          #syncUser,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> createUser({
    required String? firstName,
    required String? lastName,
    required String? country,
    required String? state,
    required String? city,
    required String? appSource,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #country: country,
            #state: state,
            #city: city,
            #appSource: appSource,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUser(_i3.UserModel? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearUserSessionData() => (super.noSuchMethod(
        Invocation.method(
          #clearUserSessionData,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  String generateNewDocId() => (super.noSuchMethod(
        Invocation.method(
          #generateNewDocId,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateNewDocId,
            [],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateNewDocId,
            [],
          ),
        ),
      ) as String);

  @override
  _i9.Future<bool> documentExists({required String? documentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #documentExists,
          [],
          {#documentId: documentId},
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> create({
    required _i3.UserModel? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #payload: payload,
            #documentId: documentId,
            #verbose: verbose,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserModel?> get(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [documentId],
        ),
        returnValue: _i9.Future<_i3.UserModel?>.value(),
        returnValueForMissingStub: _i9.Future<_i3.UserModel?>.value(),
      ) as _i9.Future<_i3.UserModel?>);

  @override
  _i9.Future<List<_i3.UserModel>> getDocuments({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [],
          {#limit: limit},
        ),
        returnValue: _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i9.Future<List<_i3.UserModel>>);

  @override
  _i9.Future<List<_i3.UserModel>> getDocumentsWithQuery({
    required _i4.Query<_i3.UserModel>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsWithQuery,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i9.Future<List<_i3.UserModel>>);

  @override
  _i9.Future<void> update({
    required String? documentId,
    required _i3.UserModel? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> onlyUpdate({
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #onlyUpdate,
          [],
          {
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> delete({required String? documentId}) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#documentId: documentId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<_i3.UserModel?> subscribe({required String? documentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
          {#documentId: documentId},
        ),
        returnValue: _i9.Stream<_i3.UserModel?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i3.UserModel?>.empty(),
      ) as _i9.Stream<_i3.UserModel?>);

  @override
  _i9.Stream<List<_i3.UserModel>> subscribeList({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeList,
          [],
          {#limit: limit},
        ),
        returnValue: _i9.Stream<List<_i3.UserModel>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.UserModel>>.empty(),
      ) as _i9.Stream<List<_i3.UserModel>>);

  @override
  _i9.Stream<List<_i3.UserModel>> subscribeListWithQuery({
    required _i4.Query<_i3.UserModel>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeListWithQuery,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i9.Stream<List<_i3.UserModel>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.UserModel>>.empty(),
      ) as _i9.Stream<List<_i3.UserModel>>);

  @override
  String newDocId(
          {required _i4.CollectionReference<_i3.UserModel>?
              collectionReference}) =>
      (super.noSuchMethod(
        Invocation.method(
          #newDocId,
          [],
          {#collectionReference: collectionReference},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #newDocId,
            [],
            {#collectionReference: collectionReference},
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #newDocId,
            [],
            {#collectionReference: collectionReference},
          ),
        ),
      ) as String);

  @override
  _i9.Future<void> createDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required _i3.UserModel? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocument,
          [],
          {
            #collectionReference: collectionReference,
            #payload: payload,
            #documentId: documentId,
            #verbose: verbose,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserModel?> findDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
          },
        ),
        returnValue: _i9.Future<_i3.UserModel?>.value(),
        returnValueForMissingStub: _i9.Future<_i3.UserModel?>.value(),
      ) as _i9.Future<_i3.UserModel?>);

  @override
  _i9.Future<List<_i3.UserModel>> fetchDocuments({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDocuments,
          [],
          {
            #collectionReference: collectionReference,
            #limit: limit,
          },
        ),
        returnValue: _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i9.Future<List<_i3.UserModel>>);

  @override
  _i9.Future<List<_i3.UserModel>> fetchDocumentsWithQuery(
          {required _i4.Query<_i3.UserModel>? query}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDocumentsWithQuery,
          [],
          {#query: query},
        ),
        returnValue: _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.UserModel>>.value(<_i3.UserModel>[]),
      ) as _i9.Future<List<_i3.UserModel>>);

  @override
  _i9.Future<void> updateDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
    required _i3.UserModel? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateOnlyDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOnlyDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<_i3.UserModel?> subscribeToDocument({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
          },
        ),
        returnValue: _i9.Stream<_i3.UserModel?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i3.UserModel?>.empty(),
      ) as _i9.Stream<_i3.UserModel?>);

  @override
  _i9.Stream<List<_i3.UserModel>> subscribeToList({
    required _i4.CollectionReference<_i3.UserModel>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToList,
          [],
          {
            #collectionReference: collectionReference,
            #limit: limit,
          },
        ),
        returnValue: _i9.Stream<List<_i3.UserModel>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.UserModel>>.empty(),
      ) as _i9.Stream<List<_i3.UserModel>>);

  @override
  _i9.Stream<List<_i3.UserModel>> subscribeToListWithQuery({
    required _i4.Query<_i3.UserModel>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToListWithQuery,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i9.Stream<List<_i3.UserModel>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.UserModel>>.empty(),
      ) as _i9.Stream<List<_i3.UserModel>>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i7.AuthenticationService {
  @override
  ({String? firstName, String? lastName}) get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: (firstName: null, lastName: null),
        returnValueForMissingStub: (firstName: null, lastName: null),
      ) as ({String? firstName, String? lastName}));

  @override
  bool get hasFirebaseUser => (super.noSuchMethod(
        Invocation.getter(#hasFirebaseUser),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAppleSignInAvailable => (super.noSuchMethod(
        Invocation.getter(#isAppleSignInAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Stream<_i7.AuthState> get authenticatedStream => (super.noSuchMethod(
        Invocation.getter(#authenticatedStream),
        returnValue: _i9.Stream<_i7.AuthState>.empty(),
        returnValueForMissingStub: _i9.Stream<_i7.AuthState>.empty(),
      ) as _i9.Stream<_i7.AuthState>);

  @override
  String get currentUserAuthProvider => (super.noSuchMethod(
        Invocation.getter(#currentUserAuthProvider),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#currentUserAuthProvider),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#currentUserAuthProvider),
        ),
      ) as String);

  @override
  bool get isProviderGoogle => (super.noSuchMethod(
        Invocation.getter(#isProviderGoogle),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isProviderApple => (super.noSuchMethod(
        Invocation.getter(#isProviderApple),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isProviderEmail => (super.noSuchMethod(
        Invocation.getter(#isProviderEmail),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Future<bool> get canSignInWithApple => (super.noSuchMethod(
        Invocation.getter(#canSignInWithApple),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void setAuthStateToIdle() => super.noSuchMethod(
        Invocation.method(
          #setAuthStateToIdle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> initializeGoogleSignIn() => (super.noSuchMethod(
        Invocation.method(
          #initializeGoogleSignIn,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> ensureGoogleSignInInitialized() => (super.noSuchMethod(
        Invocation.method(
          #ensureGoogleSignInInitialized,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearFirebaseUserOnFreshInstall() => (super.noSuchMethod(
        Invocation.method(
          #clearFirebaseUserOnFreshInstall,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addObserver(_i7.AuthObserver? observer) => super.noSuchMethod(
        Invocation.method(
          #addObserver,
          [observer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeObserver(_i7.AuthObserver? observer) => super.noSuchMethod(
        Invocation.method(
          #removeObserver,
          [observer],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> continueWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #continueWithGoogle,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  String sha256HashNonce(String? nonce) => (super.noSuchMethod(
        Invocation.method(
          #sha256HashNonce,
          [nonce],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #sha256HashNonce,
            [nonce],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #sha256HashNonce,
            [nonce],
          ),
        ),
      ) as String);

  @override
  String nonceString(
    int? length, [
    _i11.Random? randomSecure,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #nonceString,
          [
            length,
            randomSecure,
          ],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #nonceString,
            [
              length,
              randomSecure,
            ],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #nonceString,
            [
              length,
              randomSecure,
            ],
          ),
        ),
      ) as String);

  @override
  _i9.Future<bool> continueWithApple() => (super.noSuchMethod(
        Invocation.method(
          #continueWithApple,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> reauthenticateUser({required String? password}) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateUser,
          [],
          {#password: password},
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> reauthenticateUserWithProvider() => (super.noSuchMethod(
        Invocation.method(
          #reauthenticateUserWithProvider,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  String exceptionToMessage([dynamic exception]) => (super.noSuchMethod(
        Invocation.method(
          #exceptionToMessage,
          [exception],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #exceptionToMessage,
            [exception],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #exceptionToMessage,
            [exception],
          ),
        ),
      ) as String);
}

/// A class which mocks [AlertService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlertService extends _i1.Mock implements _i7.AlertService {
  @override
  _i5.ReactiveList<_i7.AlertMixin> get alertListeners => (super.noSuchMethod(
        Invocation.getter(#alertListeners),
        returnValue: _FakeReactiveList_4<_i7.AlertMixin>(
          this,
          Invocation.getter(#alertListeners),
        ),
        returnValueForMissingStub: _FakeReactiveList_4<_i7.AlertMixin>(
          this,
          Invocation.getter(#alertListeners),
        ),
      ) as _i5.ReactiveList<_i7.AlertMixin>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void addAlertListener(_i7.AlertMixin? listener) => super.noSuchMethod(
        Invocation.method(
          #addAlertListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAlertListeners(_i3.AlertModel? alertmodel) => super.noSuchMethod(
        Invocation.method(
          #notifyAlertListeners,
          [alertmodel],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showSuccessAlert({
    required String? title,
    required String? message,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showSuccessAlert,
          [],
          {
            #title: title,
            #message: message,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showInfoAlert({
    required String? title,
    required String? message,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showInfoAlert,
          [],
          {
            #title: title,
            #message: message,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showWarningAlert({
    required String? title,
    required String? message,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showWarningAlert,
          [],
          {
            #title: title,
            #message: message,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showErrorAlert({
    required String? title,
    required String? message,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #showErrorAlert,
          [],
          {
            #title: title,
            #message: message,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showAlert(_i3.AlertModel? alert) => super.noSuchMethod(
        Invocation.method(
          #showAlert,
          [alert],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void showToast(String? message) => super.noSuchMethod(
        Invocation.method(
          #showToast,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsStorageService extends _i1.Mock
    implements _i7.SettingsStorageService {
  @override
  bool get freshInstall => (super.noSuchMethod(
        Invocation.getter(#freshInstall),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.DisplayPreferences get displayPreferences => (super.noSuchMethod(
        Invocation.getter(#displayPreferences),
        returnValue: _FakeDisplayPreferences_1(
          this,
          Invocation.getter(#displayPreferences),
        ),
        returnValueForMissingStub: _FakeDisplayPreferences_1(
          this,
          Invocation.getter(#displayPreferences),
        ),
      ) as _i3.DisplayPreferences);

  @override
  _i6.Box<dynamic> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_5<dynamic>(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeBox_5<dynamic>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i6.Box<dynamic>);

  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  void setFreshInstall() => super.noSuchMethod(
        Invocation.method(
          #setFreshInstall,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDisplayPreferences(_i3.DisplayPreferences? displayPreferences) =>
      super.noSuchMethod(
        Invocation.method(
          #setDisplayPreferences,
          [displayPreferences],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveData(
    String? key,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveData,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  T getData<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [key],
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #getData,
            [key],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #getData,
            [key],
          ),
        ),
      ) as T);

  @override
  _i9.Future<void> deleteData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteData,
          [key],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void deleteAllData() => super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<T> watch<T>() => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
        ),
        returnValue: _i9.Stream<T>.empty(),
        returnValueForMissingStub: _i9.Stream<T>.empty(),
      ) as _i9.Stream<T>);
}

/// A class which mocks [UrlLauncherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLauncherService extends _i1.Mock
    implements _i7.UrlLauncherService {
  @override
  _i9.Future<void> sendEmail(
    String? email, {
    String? query,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmail,
          [email],
          {#query: query},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openUrl(
    String? url, {
    bool? openInBrowser = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [url],
          {#openInBrowser: openInBrowser},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openEmailAppChooser() => (super.noSuchMethod(
        Invocation.method(
          #openEmailAppChooser,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [ReportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportService extends _i1.Mock implements _i7.ReportService {
  @override
  _i2.Logger get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#log),
        ),
      ) as _i2.Logger);

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  List<_i3.Report> get reports => (super.noSuchMethod(
        Invocation.getter(#reports),
        returnValue: <_i3.Report>[],
        returnValueForMissingStub: <_i3.Report>[],
      ) as List<_i3.Report>);

  @override
  _i9.Stream<List<_i3.Report>> get reportsStream => (super.noSuchMethod(
        Invocation.getter(#reportsStream),
        returnValue: _i9.Stream<List<_i3.Report>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.Report>>.empty(),
      ) as _i9.Stream<List<_i3.Report>>);

  @override
  _i4.CollectionReference<_i3.Report> get collectionReference =>
      (super.noSuchMethod(
        Invocation.getter(#collectionReference),
        returnValue: _FakeCollectionReference_2<_i3.Report>(
          this,
          Invocation.getter(#collectionReference),
        ),
        returnValueForMissingStub: _FakeCollectionReference_2<_i3.Report>(
          this,
          Invocation.getter(#collectionReference),
        ),
      ) as _i4.CollectionReference<_i3.Report>);

  @override
  int get listenersCount => (super.noSuchMethod(
        Invocation.getter(#listenersCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.Report convertFromJson(Map<String, dynamic>? json) => (super.noSuchMethod(
        Invocation.method(
          #convertFromJson,
          [json],
        ),
        returnValue: _FakeReport_6(
          this,
          Invocation.method(
            #convertFromJson,
            [json],
          ),
        ),
        returnValueForMissingStub: _FakeReport_6(
          this,
          Invocation.method(
            #convertFromJson,
            [json],
          ),
        ),
      ) as _i3.Report);

  @override
  _i4.Query<_i3.Report> getReportQuery({required String? state}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportQuery,
          [],
          {#state: state},
        ),
        returnValue: _FakeQuery_7<_i3.Report>(
          this,
          Invocation.method(
            #getReportQuery,
            [],
            {#state: state},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_7<_i3.Report>(
          this,
          Invocation.method(
            #getReportQuery,
            [],
            {#state: state},
          ),
        ),
      ) as _i4.Query<_i3.Report>);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> syncReportsByState(String? state) => (super.noSuchMethod(
        Invocation.method(
          #syncReportsByState,
          [state],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> subscribeToReports(String? state) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToReports,
          [state],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> fetchReports(String? state) => (super.noSuchMethod(
        Invocation.method(
          #fetchReports,
          [state],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> fetchReportByIds(List<String>? reportIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchReportByIds,
          [reportIds],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> subscribeToReportsByIds(List<String>? reportIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToReportsByIds,
          [reportIds],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> seedFakeReports() => (super.noSuchMethod(
        Invocation.method(
          #seedFakeReports,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String generateNewDocId() => (super.noSuchMethod(
        Invocation.method(
          #generateNewDocId,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateNewDocId,
            [],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateNewDocId,
            [],
          ),
        ),
      ) as String);

  @override
  _i9.Future<bool> documentExists({required String? documentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #documentExists,
          [],
          {#documentId: documentId},
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> create({
    required _i3.Report? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #payload: payload,
            #documentId: documentId,
            #verbose: verbose,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.Report?> get(String? documentId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [documentId],
        ),
        returnValue: _i9.Future<_i3.Report?>.value(),
        returnValueForMissingStub: _i9.Future<_i3.Report?>.value(),
      ) as _i9.Future<_i3.Report?>);

  @override
  _i9.Future<List<_i3.Report>> getDocuments({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [],
          {#limit: limit},
        ),
        returnValue: _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
      ) as _i9.Future<List<_i3.Report>>);

  @override
  _i9.Future<List<_i3.Report>> getDocumentsWithQuery({
    required _i4.Query<_i3.Report>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsWithQuery,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
      ) as _i9.Future<List<_i3.Report>>);

  @override
  _i9.Future<void> update({
    required String? documentId,
    required _i3.Report? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> onlyUpdate({
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #onlyUpdate,
          [],
          {
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> delete({required String? documentId}) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {#documentId: documentId},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<_i3.Report?> subscribe({required String? documentId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [],
          {#documentId: documentId},
        ),
        returnValue: _i9.Stream<_i3.Report?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i3.Report?>.empty(),
      ) as _i9.Stream<_i3.Report?>);

  @override
  _i9.Stream<List<_i3.Report>> subscribeList({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeList,
          [],
          {#limit: limit},
        ),
        returnValue: _i9.Stream<List<_i3.Report>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.Report>>.empty(),
      ) as _i9.Stream<List<_i3.Report>>);

  @override
  _i9.Stream<List<_i3.Report>> subscribeListWithQuery({
    required _i4.Query<_i3.Report>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeListWithQuery,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i9.Stream<List<_i3.Report>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.Report>>.empty(),
      ) as _i9.Stream<List<_i3.Report>>);

  @override
  String newDocId(
          {required _i4.CollectionReference<_i3.Report>?
              collectionReference}) =>
      (super.noSuchMethod(
        Invocation.method(
          #newDocId,
          [],
          {#collectionReference: collectionReference},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #newDocId,
            [],
            {#collectionReference: collectionReference},
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #newDocId,
            [],
            {#collectionReference: collectionReference},
          ),
        ),
      ) as String);

  @override
  _i9.Future<void> createDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required _i3.Report? payload,
    String? documentId,
    bool? verbose = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDocument,
          [],
          {
            #collectionReference: collectionReference,
            #payload: payload,
            #documentId: documentId,
            #verbose: verbose,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.Report?> findDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
          },
        ),
        returnValue: _i9.Future<_i3.Report?>.value(),
        returnValueForMissingStub: _i9.Future<_i3.Report?>.value(),
      ) as _i9.Future<_i3.Report?>);

  @override
  _i9.Future<List<_i3.Report>> fetchDocuments({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDocuments,
          [],
          {
            #collectionReference: collectionReference,
            #limit: limit,
          },
        ),
        returnValue: _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
      ) as _i9.Future<List<_i3.Report>>);

  @override
  _i9.Future<List<_i3.Report>> fetchDocumentsWithQuery(
          {required _i4.Query<_i3.Report>? query}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDocumentsWithQuery,
          [],
          {#query: query},
        ),
        returnValue: _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.Report>>.value(<_i3.Report>[]),
      ) as _i9.Future<List<_i3.Report>>);

  @override
  _i9.Future<void> updateDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
    required _i3.Report? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateOnlyDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
    required Map<String, Object?>? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOnlyDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
            #payload: payload,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<_i3.Report?> subscribeToDocument({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    required String? documentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToDocument,
          [],
          {
            #collectionReference: collectionReference,
            #documentId: documentId,
          },
        ),
        returnValue: _i9.Stream<_i3.Report?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i3.Report?>.empty(),
      ) as _i9.Stream<_i3.Report?>);

  @override
  _i9.Stream<List<_i3.Report>> subscribeToList({
    required _i4.CollectionReference<_i3.Report>? collectionReference,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToList,
          [],
          {
            #collectionReference: collectionReference,
            #limit: limit,
          },
        ),
        returnValue: _i9.Stream<List<_i3.Report>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.Report>>.empty(),
      ) as _i9.Stream<List<_i3.Report>>);

  @override
  _i9.Stream<List<_i3.Report>> subscribeToListWithQuery({
    required _i4.Query<_i3.Report>? query,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToListWithQuery,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i9.Stream<List<_i3.Report>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i3.Report>>.empty(),
      ) as _i9.Stream<List<_i3.Report>>);

  @override
  void listenToReactiveValues(List<dynamic>? reactiveValues) =>
      super.noSuchMethod(
        Invocation.method(
          #listenToReactiveValues,
          [reactiveValues],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(void Function()? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAuthenticated(_i10.User? user) => super.noSuchMethod(
        Invocation.method(
          #onAuthenticated,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onUnauthenticated() => super.noSuchMethod(
        Invocation.method(
          #onUnauthenticated,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
