name: localization
description: "Localization for Civic24"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.6"

dependencies:
  flutter:
    sdk: flutter
  
  # General Dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Package Dependencies


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Internal Packages
  rules:
    path: ../rules

  # Utility Packages
  intl_utils: ^2.8.9

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/l10n/arb/
  output_dir: lib/src/l10n/generated
