name: constants
description: "Constants for Civic24"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.6"

dependencies:
  flutter:
    sdk: flutter

  # General Dependencies

  # Package Dependencies
  localization:
    path: ../localization

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Internal Packages
  rules:
    path: ../rules

flutter:
  uses-material-design: true
