name: components
description: "UI Components for Civic24"
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.6"

dependencies:
  flutter:
    sdk: flutter
  # General Dependencies
  smooth_page_indicator: ^1.2.1
  solar_icons: ^0.0.5
  iconsax_plus: ^1.0.0
  font_awesome_flutter: ^10.4.0
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.2

  # Package Dependencies
  assets:
    path: ../assets
  constants:
    path: ../constants
  localization:
    path: ../localization
  models:
    path: ../models
  styles:
    path: ../styles
  utils:
    path: ../utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Internal Packages
  rules:
    path: ../rules

  # Utility Packages
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
