default_platform(:android)

platform :android do
  desc "This lane builds the Android app and distributes it to Firebase App Distribution for Development Flavor."
  lane :development do
    build_flutter_app(flavor: "development")
    upload_to_firebase(flavor: "development")
  end

  desc "This lane builds the Android app and distributes it to Firebase App Distribution for Staging Flavor."
  lane :staging do
    build_flutter_app(flavor: "staging")
    upload_to_firebase(flavor: "staging")
  end

  desc "This lane builds the Android app and distributes it to Firebase App Distribution for Production Flavor."
  lane :production do
    build_flutter_app(flavor: "production")
    upload_to_firebase(flavor: "production")
  end

  private_lane :build_flutter_app do |options|
    flavor = options[:flavor]
    sh("flutter build apk --flavor #{flavor} --dart-define-from-file secrets/#{flavor}.json")
  end

  private_lane :upload_to_firebase do |options|
    flavor = options[:flavor]
    firebase_app_id = case flavor
      when "development" then "1:906124586309:android:86fa765f1c8e9fc989622c"
      when "staging" then "1:906124586309:android:a889a6b909f62f0589622c"
      when "production" then "1:906124586309:android:ed6729a97a7bd5fb89622c"
    end

    apk_path = File.expand_path("../../../build/app/outputs/flutter-apk/app-#{flavor}-release.apk", __FILE__)
    # service_credentials_file = File.expand_path("../../../firebase_service_account.json", __FILE__)

    firebase_app_distribution(
      app: firebase_app_id,
      apk_path: apk_path,
      release_notes: "This is a new release of the app for Civic24 #{flavor}. Please test and provide feedback",
      firebase_cli_path: "/usr/local/bin/firebase",
      testers: "jesuseguncaleb@gmail.com, danieljesusegun@gmail.com, deborahjesusegun@gmail.com, justusjesuse@gmail.com",
    #   service_credentials_file: service_credentials_file
    )
  end
end