name: 🏷️ Pull Request Labeling

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  assign_author:
    name: 🙋‍♂️ Assign Author to PR
    permissions:
      contents: none
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 🔗 Auto-assign PR author
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: 🏷️ Add PR Labels
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Label PR by branch name
        uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5.0.0
        with:
          configuration-path: .github/pr-labeling/branch-name.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧠 Label PR by file changes
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
        with:
          configuration-path: .github/pr-labeling/file-changes.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
